### ISSUE TITLE
buffer ".sort()", inconsistnet

### ISSUE THREAD

**Issue by masa300V** [shun/ddu-source-buffer#6]
Thanks for this great plugin.

I noticed that buffer sorting is violating the symmetric requirements and brings me, say 50-50 chance, good sorting and no-sorting at this  code.

> sort((a, b) => { return a.bufnr == currentBufNr ? -1 : a.lastused - b.lastused;   })

I think this JS reference statement, of .sort() method, applies to this case.  Above code is not symmetric.

>  Symmetric: compareFn(a, b) and compareFn(b, a) must both be 0 or have opposite signs.

My personal folk works with code like this.  I'm not good at JS and can be clean up more but it works.
Here, I override the lastused on the current buffer before soting.
Then, I pushed current buffer to the bottom, at .sort(), and alt-buf to the top.

> buffers.forEach(function(b){ if (b.bufnr == currentBufNr){ b.lastused = 0;  }; });
> ....
> .sort((a, b) => { return b.lastused - a.lastused; })

best regards,
Masashi

**Comment by shun** [comment]
I'm sorry to give you late feedback.
I have to re-install the os for my pc.
However I can't do this by 6th of Nov.
I will check this later.

**Comment by shun** [comment]
fixed [a2b0874](https://github.com/shun/ddu-source-buffer/commit/a2b08740d78dc2a6ecbd580660fe77860f55866c).
