### ISSUE TITLE
Current buffer is always "ddu"

### ISSUE THREAD

**Issue by masa300V** [shun/ddu-source-buffer#7]
Thanks for this great plugin.

I noticed that current buffer is missing on the ":Ddu buffer" command.
After tracing the code, I see that "a buffer of ddu is always the current" and filtered-out as it's not "listed" when we call "ddu#source#buffer#getbufinfo()" inside the ddu.

I propose to take a snapshot of buffer list before invoking ddu, store the snapshot in a variable, inside ddu just refer to the snapshot.

- I renamed the contents of original "ddu#source#buffer#getbufinfo()" as ddu#source#buffer#getsnapshot().
- I put the buffer list snapshot (before ddu) into a temporary variable.
- My new "ddu#source#buffer#getbufinfo()" is just returning the snapshot from the variable.
- I call :Ddu buffer like this way on my mapping.

> nnoremap <silent> <Leader>bb :<C-u>call ddu#source#buffer#getsnapshot()<CR> :call ddu#start({'sources': [{'name': 'buffer'}]})<CR>

**Comment by shun** [comment]
Let me check what you mention below;
> I noticed that current buffer is missing on the ":Ddu buffer" command.

This means that you can't see the current buffer name on the list when you execute ":Ddu buffer", right ?
Could you tell me your environment ?
My vim environment is below.
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov 09 2022 23:55:52)
macOS 版 - arm64
適用済パッチ: 1-850
Compiled by Homebrew
```
https://user-images.githubusercontent.com/212602/201125741-967680c9-9463-4c98-8fc5-f75c073618e1.mov

Probably, I can't get what you mention correctly.
So, let's discuss this in Japanese, if you can.

Thank you.

**Comment by masa300V** [comment]
I'm sorry for my too short report.
My system info:

> NVIM v0.8.0-1210-gd367ed9b2, windows 64bit binary downloaded from the official site
> INFO: Detected Deno version: `1.26.1`

What I meant is I don't see a "current buffer **mark %**" is not on the current buffer as a result of :Ddu Buffer.

***

Sorry in Japanese.  日本語で書きます。

Deniteと同じ感じで、バッファのリストが出て欲しいと思ってます。
狙いは、:Ddu Bufferにて、Altバッファがトップで、カレントバッファがボトムです。
自分の指が、一個手前のバッファに戻るのに、「ddu bufferで、リストを見ずにリターン」に慣れているためです。
ここまでは、本筋ではなくて、経緯です。

自分のデバッグ用のfolkを作って、どうなっているかを追うと、current bufferは、いつもDDUのバッファになっています。ここで、DDUのバッファは、listedではないので、フィルターで弾かれて"%"は、どこにも表示されません。
さらには、私のもう片方のレポートでのソートが入りません。
current bufferがDDUに移行しているので、自動的にDDU起動まえに、altのバッファと思っていたバッファはマークがなくなって、DDU起動前にcurrentだったものがaltになります。

自分用に、自分の好きな動作にするためには、DDU起動前に、バッファのスナップショットをとって、これをsource-bufferに食わせると、私の希望の動きになってます。

古い人間なもので、githubにて、どうしたらいいのか別らないので、ここでレポートしてます。私のfolkでは、2つのレポート内容が動くようになってます。

**Comment by shun** [comment]
詳細は説明ありがとうございます。
deniteと同じ感じということですね。
なるほどです。
週末考えてみたいと思います。
また、ソースの方も参考にさせていただきたいと思います。

この辺、皆さんmru使う人も多そうで、その辺はどっちが良いのかなぁと思ってるところはありました。

**Comment by masa300V** [comment]
ご検討、ありがとうございます。
わたしが、neovimを使っているプロジェクトの性格上、多数のファイルを開いて、でも半数以上はeditせず参照していたりします。そうして、だんだん、どのバッファをエディットしたか分からなくなります。こうなると、バッファのリストのエディットした/しないマークがどうしても欲しくなります。
私も、その日のnvimを開くと、MRUから始めます。だんだん、ddu filerになって、必要なファイルが開かれるとddu bufferです。

**Comment by shun** [comment]
挙動などなど理解しました。
current/alt、全く意味をなしてなかったですね。。。すみません。
なんとなく、ddu本体側にも手を入れないと解決できなさそうな気もしています。

提案頂いた方法も無くはないと思うのですが、かなりイレギュラーな仕組になるかと思うので、
この方式を恒久策とするのは控えたいかなと思っています。
一旦、 @masa300V さんの方で手を入れたパッチで問題ないのであればそのまま使っていただき、
対策を考えたいと思います。

案としては、２つくらいかなぁと思っています。
・ddu側でgatherをコールしてからddu-ff-defalut を表示するオプションを追加
・ddu側でUIを表示する前に実行するプリフェッチ的なI/Fを増やす

でもどちらの案もこのプラグインだけしか使わなさそうな仕組のため、他になにか考えたいなと思っています。
。。。と書いているうちに、このプラグインでコマンドを提供して、そのコマンド内で @masa300V さんのように
dduのstart実行する前に変数に入れるであれば、使っている方にトリッキーなマッピングを強要しなくても
良さそうな。。。

```
function! ddu_buffer#listup() abort
  let g:ddu_buffer_bufinfo = ddu#source#buffer#getbufinfo()
  call ddu#start({'sources': [{'name': 'buffer', 'params': {}}]})
endfunction
```

でも、他のプラグインと同じ感じに使えないので、控えたいですね。
考えますがお時間ください。

**Comment by shun** [comment]
fixed [a2b0874](https://github.com/shun/ddu-source-buffer/commit/a2b08740d78dc2a6ecbd580660fe77860f55866c).
Please set `orderby` option as `desc`, so you can get the list as your expected.

ソートオプションを追加しました。
`orderby`オプションで `desc` を設定していただければ、意図したソートになるかと思います。
[参考](https://github.com/shun/vimrc/commit/9caa6ed849a738f44230f91e39477d66a569dc66)
