### ISSUE TITLE
Is it possible to close a buffer through the UI?

### ISSUE THREAD

**Issue by jeffwillette** [shun/ddu-source-buffer#8]
I am wondering if it is possible to close a buffer with this source through the UI with a key remapping. 

For example, could I remap `d` to close an open buffer than is shown in the UI? Is this source the right place to even place this responsibility? Or should I look elsewhere?

**Comment by shun** [comment]
@jeffwillette 
Thanks for your feedback.

Let me understand what you pointed out.
1. Show buffer list by ddu.
2. Press `d` on the list which you want to delete the buffer.
3. Execute like `bd` command then the buffer deleted.

Is this what you expected behavior ?

If yes, I don't implement the delete buffer event feature so far.

**Comment by jeffwillette** [comment]
> @jeffwillette Thanks for your feedback.
> 
> Let me understand what you pointed out.
> 
> 1. Show buffer list by ddu.
> 2. Press `d` on the list which you want to delete the buffer.
> 3. Execute like `bd` command then the buffer deleted.
> 
> Is this what you expected behavior ?
> 
> If yes, I don't implement the delete buffer event feature so far.

Yes, this is the behavior I was asking about. It would be really convenient for deleting buffers. But I am not sure if this is the correct ddu plugin which should handle such an operation. Is this plugin the right place to put this?

**Comment by shun** [comment]
@jeffwillette 

I implemented the delete buffer action.
Please update the plugin and set as below then try it.
Hopefully, it's solved.

```
[plugins.ftplugin]
ddu-ff = '''
nnoremap <buffer><silent> d
    \ <Cmd>call ddu#ui#ff#do_action('itemAction', {'name': 'delete'})<CR>
'''
```

You can also see my [vimrc](https://github.com/shun/vimrc/commit/80d1127759204cfae829f9ef35ba7c28cfa276d8).

**Comment by jeffwillette** [comment]
Wow. Works great! Thanks
